- name: Create CQ service
  hosts: "extractors_cq"
  become: true

  tasks:
  # Setup dependencies
  - name: install dependencies
    apt:
        name: "{{item}}"
        state: present
        update_cache: yes
    loop:
        - python3
        - python3-pip
    environment:
      DEBIAN_FRONTEND: noninteractive
  - name: install pip dependencies
    ansible.builtin.pip:
      name:
          - pandas
          - grpcio  
          - grpcio-tools

  #Copy own files and start qc services
  - name: mkdir repository src
    ansible.builtin.file:
        path: /home/adminasier/src/cq
        state: directory
  - name: copy src files
    ansible.builtin.copy:
        src: /home/asier/cloud/MaquinasVirtuales/Extractors/ChemicalCompositionExtractor/
        dest: /home/adminasier/src/cq
        remote_src: no
  - name: Change permissions for python files
    ansible.builtin.command:
      cmd: sudo chmod -R 777 /home/adminasier/src/
  - name: mkdir for cq file 
    ansible.builtin.file:
        path: /home/adminasier/DB/Repositorios/storage/file_input/data/
        state: directory
  - name: copy cq files
    ansible.builtin.copy:
        src: /home/asier/cloud/MaquinasVirtuales/DB/Repositorios/storage/file_input/data/cq.csv
        dest: /home/adminasier/DB/Repositorios/storage/file_input/data/cq.csv
        remote_src: no
  - name: mkdir logs 
    ansible.builtin.file:
        path: /home/adminasier/logs/
        state: directory
  - name: Touch a log file
    ansible.builtin.file:
      path: /home/adminasier/logs/ChemicalCompositionExtractor.txt
      state: touch
      mode: u=rw,g=rw,o=rw
      
  #Execute the script
  - name: execute python in background (shell)
    ansible.builtin.shell: nohup python3 src/cq/src/main.py --start > /dev/null 2>&1 &
    args:
      chdir: /home/adminasier