- name: Create DB service
  hosts: "grpc"
  become: true

  tasks:
  # Setup dependencies
  - name: install dependencies
    apt:
        name: "{{item}}"
        state: present
        update_cache: yes
    loop:
        - python3
        - python3-pip
    environment:
      DEBIAN_FRONTEND: noninteractive
  - name: install pip dependencies
    ansible.builtin.pip:
      name:
          - grpcio  
          - grpcio-tools

  #Copy own files and start grpc services
  - name: mkdir repository src
    ansible.builtin.file:
        path: /home/adminasier/src/grpc
        state: directory
  - name: copy src files
    ansible.builtin.copy:
        src: /home/asier/cloud/MaquinasVirtuales/gRPC_Relay_Server/
        dest: /home/adminasier/src/grpc/
        remote_src: no
  - name: Change permissions for python files
    ansible.builtin.command:
      cmd: sudo chmod -R 777 /home/adminasier/src/
  - name: mkdir logs 
    ansible.builtin.file:
        path: /home/adminasier/src/logs/
        state: directory
  - name: execute python in background (shell)
    ansible.builtin.shell: nohup python3 grpc/gRPC_Relay_Server_Topic.py > /dev/null 2>&1 &
    args:
      chdir: /home/adminasier/src