apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdagent-file-input-deployment
  namespace: cloudnamespace

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pdagent-file-input
  template:
    metadata:
      labels:
        app: pdagent-file-input
    spec:

      containers:
      - name: pdagent-file-input
        image: pdagent_file:0.1
        imagePullPolicy: Never
        env:
          - name: KAFKA_BROKER_IP
            value: kafka-service
          - name: KAFKA_BROKER_PORT
            value: '29093'
          - name: KAFKA_MYSQL_PROCESS_TOPIC
            value: chemical_composition_file
          - name: COMPOSITION_FILE_PATH
            value: /usr/src/app/cqfile/cq.csv
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 29093
        volumeMounts:
          - name: file
            mountPath: /usr/src/app/cqfile/
 
      volumes:
        - name: file
          hostPath:
            path: /input/
        
      


