apiVersion: v1
kind: Service
metadata:
  name: pdagent-file-input-service
  namespace: cloudnamespace

spec:
  selector:
    app: pdagent-file-input
  ports:
    - name: kafka-port
      port: 9092         # Port exposed within the cluster
      targetPort: 9092   # Port on the pods