apiVersion: v1
kind: Service
metadata:
  name: pdagent-file-input-service
  namespace: cloudnamespace

spec:
  selector:
    app: pdagent-file-input
  ports:
    - name: kafka-port
      port: 29093         # Port exposed within the cluster
      targetPort: 29093   # Port on the pods