apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdagent-mysql-input-deployment
  namespace: cloudnamespace

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pdagent-mysql-input
  template:
    metadata:
      labels:
        app: pdagent-mysql-input
    spec:

      containers:
      - name: pdagent-mysql-input
        image: pdagent_mysql:0.1
        imagePullPolicy: Never
        env:
          - name: KAFKA_BROKER_IP
            value: kafka-service
          - name: KAFKA_BROKER_PORT
            value: '29093'
          - name: KAFKA_MYSQL_PROCESS_TOPIC
            value: pouring_mysql
          - name: MYSQL_IP
            value: mysql-input-service
          - name: MYSQL_PORT
            value: '3306'
          - name: MYSQL_ROOT_PASSWORD
            value: MUCSI_Deusto2022 
          - name: MYSQL_DB
            value: app_db 
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            value: MUCSI_Deusto2022
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 29093
        - containerPort: 3306
        
      


