# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relay.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brelay.proto\x12\x05relay\"\'\n\x07Message\x12\r\n\x05topic\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\".\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x12\n\x10PublishConfirmed\"!\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t2\x85\x01\n\x0cRelayService\x12;\n\x07Publish\x12\x15.relay.PublishRequest\x1a\x17.relay.PublishConfirmed\"\x00\x12\x38\n\tSubscribe\x12\x17.relay.SubscribeRequest\x1a\x0e.relay.Message\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relay_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=22
  _globals['_MESSAGE']._serialized_end=61
  _globals['_PUBLISHREQUEST']._serialized_start=63
  _globals['_PUBLISHREQUEST']._serialized_end=109
  _globals['_PUBLISHCONFIRMED']._serialized_start=111
  _globals['_PUBLISHCONFIRMED']._serialized_end=129
  _globals['_SUBSCRIBEREQUEST']._serialized_start=131
  _globals['_SUBSCRIBEREQUEST']._serialized_end=164
  _globals['_RELAYSERVICE']._serialized_start=167
  _globals['_RELAYSERVICE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
