# Docker-compose for creating DBs

version: "3"
networks:
  cloud-network:
    driver: bridge
services:
  # We create the services for the data bases (input and ouput)
  mysql-input:       
    restart: always
    image: mysql:8.1
    container_name: mysql-input
    environment:
      MYSQL_ROOT_PASSWORD: MUCSI_Deusto2022
      MYSQL_DATABASE: app_db
      MYSQL_USER: mucsi
      MYSQL_PASSWORD: MUCSI_Deusto2022
    ports:
      - "3306:3306"
    volumes:
      - ./Storage/MySql_Input/data/db:/var/lib/mysql
    networks:
      - cloud-network