# Docker-compose for creating DBs

version: "3"
networks:
  cloud-network:
    driver: bridge
services:
  # We create the services for the data bases (input and ouput)
  mysql-input:       
    restart: always
    image: mysql:latest
    container_name: mysql-input
    environment:
      MYSQL_ROOT_PASSWORD: MUCSI_Deusto2022
      MYSQL_DATABASE: app_db
      MYSQL_USER: mucsi
      MYSQL_PASSWORD: MUCSI_Deusto2022
    ports:
      - "3306:3306"
    volumes:
      - ./Storage/MySql_Input/data/db:/var/lib/mysql
    networks:
      - cloud-network
  
  # Version for Mac Silicom and all systems
  sqlserver-input:  
    restart: always  
    container_name: sqlserver-input
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: MUCSI_Deusto2022
      MSSQL_PID: Developer
    volumes:
      - ./Storage/azure-sql-edge/data:/var/opt/mssql/data 
      - ./Storage/azure-sql-edge/log:/var/opt/mssql/log 
      - ./Storage/azure-sql-edge/secrets:/var/opt/mssql/secrets  
    networks:
      - cloud-network
    
  postgres-output:
    restart: always
    container_name: postgres-output
    # We use version 15 because the data folder was alredy prepared for that version (we will have problems for 16). 
    # This is an example that we do not need to use the last version and we can keep the way of working inside the container.
    image: 'postgres:15' 
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=MUCSI_Deusto2022
      - POSTGRES_DB=Foundry_Relational_Storage
    volumes:
      - './Storage/Relational_Output/data:/var/lib/postgresql/data'
    networks:
      - cloud-network
  
  # FYI: There is a file in config during creation (maybe with mac silicon) that we need to make a chmod 666. 
  # In fact, I have changed all files in the config folder. After this, influx BD is running. 
  influxdb-output:
      restart: always
      container_name: influxdb-output      
      image: 'influxdb:latest'
      ports:
          - '8086:8086'
      environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup # first time configure all
        - DOCKER_INFLUXDB_INIT_USERNAME=root 
        - DOCKER_INFLUXDB_INIT_PASSWORD=MUCSI_Deusto2022 
        - DOCKER_INFLUXDB_INIT_ORG=Deusto 
        - DOCKER_INFLUXDB_INIT_BUCKET=cloud-bucket 
        - DOCKER_INFLUXDB_INIT_RETENTION=1w 
      volumes:
        - './Storage/influxdb2/data:/var/lib/influxdb2'
        - './Storage/influxdb2/config:/etc/influxdb2'
      networks:
        - cloud-network
  

  
  


  
 
  
  

  