apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-output-deployment
  namespace: cloudnamespace

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: influx-output
  template:
    metadata:
      labels:
        app: influx-output
    spec:

      containers:
      - name: influx-output
        image: mysql:8.1
        imagePullPolicy: Always
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: MUCSI_Deusto2022
          - name: MYSQL_DATABASE
            value: app_db
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 8086
        volumeMounts:
          - name: influx-init-data
            mountPath: /var/lib/influxdb2
          - name: influx-init-data
            mountPath: /etc/influxdb2
            
      volumes:
        - name: influx-init-data
          persistentVolumeClaim:
            claimName: influx-output-data-pvc
        - name: influx-init-config
          persistentVolumeClaim:
            claimName: influx-output-config-pvc
 
      


