apiVersion: v1
kind: Service
metadata:
  name: influx-output-service
  namespace: cloudnamespace

spec:
  type: NodePort
  selector:
    app: influx-output
  ports:
    - port: 8086         # Port exposed within the cluster
      targetPort: 8086   # Port on the pods
      nodePort: 30004    # Port accessible externally on each node