apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-input-pv
  namespace: cloudnamespace
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureDisk:
    kind: Managed
    diskName: mysql-disk
    diskURI: /subscriptions/16a94b55-2151-4fa9-8684-2ad3cd089429/resourceGroups/cloud_rg/providers/Microsoft.Compute/disks/mysql-disk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-input-pvc
  namespace: cloudnamespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi