apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-input-pv
  namespace: cloudnamespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mysql-input-data   # Cambia esta ruta si usas minikube mount
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-input-pvc
  namespace: cloudnamespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi