apiVersion: v1
kind: Service
metadata:
  name: mysql-input-service
  namespace: cloudnamespace

spec:
  type: NodePort
  selector:
    app: mysql-input
  ports:
    - port: 3306         # Port exposed within the cluster
      targetPort: 3306   # Port on the pods
      nodePort: 30001    # Port accessible externally on each node