apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-output-deployment
  namespace: cloudnamespace

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres-output
  template:
    metadata:
      labels:
        app: postgres-output
    spec:
    
      containers:
      - name: postgres-output
        image: postgres:15
        imagePullPolicy: Always
        env:
          - name: POSTGRES_PASSWORD
            value: MUCSI_Deusto2022
          - name: POSTGRES_DB
            value: Foundry_Relational_Storage
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgres-output-data-pvc
            mountPath: /var/lib/postgresql/data/
          # - name: postgres-data
          #   mountPath: /var/lib/postgresql/data
          
      volumes:
        - name: postgres-output-data-pvc
          persistentVolumeClaim:
            claimName: postgres-output-pvc
        # - name: postgres-data
        #   persistentVolumeClaim:
        #     claimName: postgres-output-pvc

        
      


