apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-output-pv
  namespace: cloudnamespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /db_data/postgres/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-output-pvc
  namespace: cloudnamespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi