apiVersion: v1
kind: Service
metadata:
  name: postgres-output-service
  namespace: cloudnamespace

spec:
  type: NodePort
  selector:
    app: postgres-output
  ports:
    - port: 5432         # Port exposed within the cluster
      targetPort: 5432   # Port on the pods
      nodePort: 30003    # Port accessible externally on each node