apiVersion: v1
kind: Service
metadata:
  name: sqls-input-service
  namespace: cloudnamespace

spec:
  type: NodePort
  selector:
    app: sqls-input
  ports:
    - port: 1433         # Port exposed within the cluster
      targetPort: 1433   # Port on the pods
      nodePort: 30002    # Port accessible externally on each node