# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from communication.service import relay_pb2 as relay__pb2


class RelayServiceStub(object):
    """gRPC service (RelayService)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/relay.RelayService/Publish',
                request_serializer=relay__pb2.PublishRequest.SerializeToString,
                response_deserializer=relay__pb2.PublishConfirmed.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/relay.RelayService/Subscribe',
                request_serializer=relay__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=relay__pb2.Message.FromString,
                )


class RelayServiceServicer(object):
    """gRPC service (RelayService)
    """

    def Publish(self, request, context):
        """Publish RPC - takes a PublishRequest with a topic and value field
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe RPC takes a SubscribeRequest and returns a stream 
        of Message objects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=relay__pb2.PublishRequest.FromString,
                    response_serializer=relay__pb2.PublishConfirmed.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=relay__pb2.SubscribeRequest.FromString,
                    response_serializer=relay__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relay.RelayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RelayService(object):
    """gRPC service (RelayService)
    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relay.RelayService/Publish',
            relay__pb2.PublishRequest.SerializeToString,
            relay__pb2.PublishConfirmed.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/relay.RelayService/Subscribe',
            relay__pb2.SubscribeRequest.SerializeToString,
            relay__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
