apiVersion: v1
kind: Service
metadata:
  name: cooling-drum-water-prediction-service
  namespace: cloudnamespace

spec:
  type: NodePort
  selector:
    app: cooling-drum-water-prediction
  ports:
    - port: 80         # Port exposed within the cluster
      targetPort: 80   # Port on the pods
      nodePort: 30080  # Port accessible externally on each node