apiVersion: v1
kind: Service
metadata:
  name: kafdrop-service
  namespace: cloudnamespace

spec:
  selector:
    app: kafdrop
  ports:
    - name: kafdrop-internal
      port: 9000        
      targetPort: 9000 
    - name: kafka-broker-connect
      port: 9092        
      targetPort: 9092  