apiVersion: v1
kind: Service
metadata:
  name: kafdrop-service
  namespace: cloudnamespace

spec:
  selector:
    app: kafdrop
  ports:
    - name: kafdrop-external
      port: 9000        
      targetPort: 9000 