apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: cloudnamespace

spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181         # Port exposed within the cluster
      targetPort: 2181   # Port on the pods