apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-log-pv
  namespace: cloudnamespace
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: zookeeper-log
    volumeAttributes:
      shareName: zookeeper-log
    nodeStageSecretRef:
      name: azure-files-secret
      namespace: cloudnamespace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-log-pvc
  namespace: cloudnamespace
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data-pv
  namespace: cloudnamespace
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: zookeeper-data
    volumeAttributes:
      shareName: zookeeper-data
    nodeStageSecretRef:
      name: azure-files-secret
      namespace: cloudnamespace
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data-pvc
  namespace: cloudnamespace
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
