apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  namespace: cloudnamespace

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:

      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        imagePullPolicy: Always
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 2181
        volumeMounts:
          - name: kafaka-data
            mountPath: /var/lib/zookeeper/data
          - name: kafaka-logs
            mountPath: /var/lib/zookeeper/log
 
      volumes:
        - name: kafaka-data
          persistentVolumeClaim:
            claimName: zookeeper-data-pvc
        - name: kafaka-logs
          persistentVolumeClaim:
            claimName: zookeeper-log-pvc

        
      


