apiVersion: v1
kind: Service
metadata:
  name: belts-water-addition-factor-service
  namespace: cloudnamespace

spec:
  type: NodePort
  selector:
    app: belts-water-addition-factor
  ports:
    - port: 80         # Port exposed within the cluster
      targetPort: 80   # Port on the pods
      nodePort: 30081  # Port accessible externally on each node